### ISSUE TITLE
#loadedPackageOfClass: gives walkback

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#10]
Executing this bit of smalltalk code yields a walkback: 

Rowan loadedPackageOfClass: Object 

MessageNotUnderstood >> defaultAction @3 line 3
MessageNotUnderstood (AbstractException) >> _signalWith: @6 line 25
MessageNotUnderstood (AbstractException) >> signal @2 line 47
RwGsLoadedPackage class (Object) >> doesNotUnderstand: @10 line 10
RwGsLoadedPackage class (Object) >> _doesNotUnderstand:args:envId:reason: @8 line 13
RwGsPlatform >> loadedPackageOfClass: @3 line 4
Rowan class >> loadedPackageOfClass: @2 line 4
Executed Code  @2 line 1 
GsNMethod class >> _gsReturnToC @1 line 1
~

**Comment by dalehenrich** [comment]
Right, that's because Object does not (yet) have a package and I have 
not worked through the vagaries of reasoning about loaded things that 
are not packaged ... which is why I think a customized Rw*Definition 
with enhanced properties is the way to go --- then under the covers I 
can provide a uniform set of objects whether or not they are packaged or 
not ...

Dale

**Comment by ericwinger** [comment]
I thought that if a class doesn't have a package, it should just return nil. No?

**Comment by dalehenrich** [comment]
... No :)

**Comment by dalehenrich** [comment]
@ericwinger and I decided that the solution is to add `rowanPackageName` and `rowanProjectName` methods to **Class** and **GsNMethod,** so that a message can be set  to the object in question  ... if the class or method is not packaged the string `'(NONE)'` is returned ... presumably need to add logic to the places where package names and project names are handled, so that the  `'(NONE)'` package or project will succeed despite the fact that there is no packaging -- on second thought this  will have take more thought ---for now,  it won't be legal to use `'(NONE)'` in the API ...
