### ISSUE TITLE
Add Jadeite version to window title

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#110]
This will help us note the version while screenshotting for issues during the alpha development.

**Comment by LisaAlmarode** [comment]
The title bar text is: Jadeite version <0.9.4 url:git@github.com:erciwinger/Jade.git> 1 (SystemUser) - Rowan System Browser on stone3215 session 5 on localhost with remote gem on benton

Objections: I don't like to see a github reference, nor erciwinger's name, and certainly not the obsolete name Jade.

The version number immediately preceded by < looks like the version number was "before 0.9.4"... I don' see value in any brackets, but square rather than angle would be better. 

And the whole is too long, with most of the useful information trailing at the end.  I do rely on the popup in the windows toolbar and with these titles, most of the actual part you need to know about the windows is truncated.



What I'd most like:

Jadeite version 0.9.4 - Rowan System Browser on stone3215 session 2 for SystemUser with remote gem on benton

(Note the GemStone session replaced with the Jadeite session)
