### ISSUE TITLE
unexpected results sending #rowanPackageName and #rowanProjectName to method 

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#21]
Even though I created the method MyNewClass>>createdWithRowan with the rwCompileMethod:category and MyNewClass is a rowan-aware class, sending ```rowanPackageName``` and ```rowanProjectName``` to the compiled method returns (NONE)

Sending the same methods to the compiled method ```fnoodle3``` correctly finds the package and project.

**Comment by dalehenrich** [comment]
well something seems to be wrong somewhere ... will have to get my hands on those things ... methods need to be identical, so it may depend upon when you grab the method in relation to when you've lat updated the method ...

**Comment by ericwinger** [comment]
I've been digging around and trying to learn more. In the test 340 stone I can create a new stone with the smalltalk rowan api, then create a method on it and send the above methods to see the failure.

```Object rwSubclass: 'MyNewClass4'
	instVarNames: #( bbb)
	classVars: #()
	classInstVars: #()
	poolDictionaries: #()
	category: 'Rowan-Dummy'
	options: #()```

Maybe this will help you debug.

**Comment by dalehenrich** [comment]
Well I have tests that do what you are describing and they are passing, so more explicit code is needed ... I'm sure that there is a bug here, but since I have a number of tests that are covering several different angles, I need to know exactly what code you are executing ... I still don't know how you are grabbing the method instances that are failing ... so I just need details ... sitting down with you and debugger will be the best way ...

**Comment by ericwinger** [comment]
There was a double compile built in to Jade. When the second 'normal' compile was run after the rowan compile, things got wonky.
