### ISSUE TITLE
senders of #halt reveal many in test_rowan_340 server

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#39]
Doing a sender of #halt reveals a long list in the server. 

It's unclear how many of these should be cleaned up before the pilot project is released to the customer.

**Comment by dalehenrich** [comment]
There are only a handful of senders of `halt` in Rowan and these should be cleaned up (obviously none of them are sent as a result of the current test suite):
```
 RwGsImagePatchVisitor>>visitPropertiesModification:
 RwGsImagePatchVisitor>>visitSourceModification:
 RwGsPackageSymbolDictionary>>addClassAssociation:forClass:toPackageNamed:
 RwPackageModification>>addModificationToPatchSet:inPackage:
```
The rest of the offenders are in the base, GLASS or tODE and can be ignored, since we won't be shipping Rowan in 3.2.15 with GLASS or tODE installed ...

**Comment by ericwinger** [comment]
Sounds good.

**Comment by dalehenrich** [comment]
unclosing so that we will make a sanity check before shipping to make sure that Rowan `self halts` are removed

**Comment by dalehenrich** [comment]
`halts` in Rowan code have been eliminated ...
