### ISSUE TITLE
Load package failed

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#52]
Trying to load 'RowanSimple1' and got this walkback. 

```
a MessageNotUnderstood occurred (error 2010), a UndefinedObject does not understand  #'asRwRepository'
MessageNotUnderstood >> defaultAction @3 line 3
MessageNotUnderstood (AbstractException) >> _signalWith: @6 line 25
MessageNotUnderstood (AbstractException) >> signal @2 line 47
UndefinedObject (Object) >> doesNotUnderstand: @10 line 10
UndefinedObject (Object) >> _doesNotUnderstand:args:envId:reason: @8 line 13
RwPrjReadTool >> readProjectSetForProjectNamed: @8 line 5
RwPrjLoadTool >> loadProjectNamed: @5 line 7
RowanProjectService >> loadProjectNamed: @4 line 3
GsNMethod class >> _gsReturnToC @1 line 1

```
I'm just calling this code with 'RowanSimple1'
```
Rowan projectTools load loadProjectNamed: aName
```

**Comment by dalehenrich** [comment]
From the stack it looks like you are executing the [following line](https://github.com/dalehenrich/Rowan/blob/master/src/tonel/Rowan-Tools/RwPrjReadTool.class.st#L12):
```smalltalk
	repo := projectDefinition repositoryUrl asRwRepository.
```
and to get a nil back from repositoryUrl, likely means that the spec that you are using was not correctly created ... sooo I am somewhat suspicious about the provenance of the loadedProject specification that you are using (and of course the possibility of a bug:) --- but either way the *damage* was done by the steps leading up to you running `RowanProjectService >> loadProjectNamed:` ... my best guess with the information I have right now is that you had an error while doing the initial load of the `.ston` file and rather than *deleting all projects* --- because the *incomplete* project might have showed up in the project list --- you tried doing a load and **kaboom** ... but I am guessing without any concrete evidence:)

**Comment by ericwinger** [comment]
The prior step was clone the git repository. I had a number of troubles related to Dolphin issues. Although I got the Dolphin issues resolved, it may have left the project in a bad state.
