### ISSUE TITLE
need clarity on when Rowan objects become referenceable by name

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#7]
Too often, I either can't reference an Rowan object (method, class, package, project) by name when I think I should, or I inadvertently try to 're-add' an object that I added before because I referenced it's name. 

Here is one use case:
1. Create a project definition. 
2. Load it by - ... projectTools load loadProjectDefinition:. 
2. Add a package definition by sending #addPackageNamed: to the project definition. 
3. Add a class by sending #addClass:inPackageNamed:inProject: to projectTools.
4. Try to add method with browserTool by sending addOrUpdateMethod:inProtocol:... get 'class not found' error. 
5. Go back to Step 3 and 'reload' the project definition after adding the class gets 'attempt to add existing package'

I'm unable to get around this.

**Comment by dalehenrich** [comment]
Could you provide a code snippet to illustrate what you are doing ....

 step 3 is suspicious to me, because editing a project definition without doing a load does not add the package to the system ... at which point I would expect step 4 to fail because the package presumably has not been created ... but it succeeds for you ... sho there appears to be a bug there ...

I guess I am curious why you did step 6 (which re-creates a package) when the the error is that the class is not defined ... presumably a bug in #addClass:inPackageNamed:inProject: (as I mentioned earlier) ...

If you provide some code, I won't have to guess and I will be able to zero in on the bug without any muss or fuss ...

**Comment by ericwinger** [comment]
Can you login to test_rowan_340 on foos?  If so, then step through 

RowanMethodDefinitionService new createSampleMethod

My code is scattered across several classes and makes it hard to cut/paste into this tool. However, the concept is rather simple - I start by creating a sample method, which requires creating a sample class, sample package, and sample project. The idea is that I exercise all the basic Rowan apis independently, but in one fell swoop.

**Comment by dalehenrich** [comment]
I can execute code in test_rowan_340, so this is perfect...

**Comment by dalehenrich** [comment]
As an aside, how are you managing the source code that you are loading into test_rowan_340? It doesn't appear that you are using Monticello packages, so I guess you are using .gs files and GBS?

I was about to make some changes to the code in your stone, but then realized that you wouldn't know what I did ... I was thinking that it might make sense to put the server-side code for the client into Rowan in a `Rowan-Client` package ... then I'd also be able to work with that code in the safety of my own image and then supply pull requests that you code review before incorporating into your code base ... an d in proactical terms, I would be able to run tests against the client code-base when I'm making changes so that I could avoid breaking the client code while making my own changes ...

The Rowan code can be saved using tODE commands ... which you could run from your image ... code diffs are available in tODE. but with not too much work, you'd be able to see a string-based diff of the code (using a tODE Smalltalk API) ... tODE get's its' diffs using Text objects so I get bold and colorized diffs ... we should do this on Monday when I am in the office ... if it makes sense to you?

**Comment by ericwinger** [comment]
Right now, everything is stored in SymbolDictionary - RowanServices. 
I file that dictionary out and manage it with git. You can always get it from
my git project - github.com/ericwinger/Jade. 

Would that work? 

Eric Winger
eric@thewingers.net
503.516.6271


Awards:
* 2017 District 7 Toastmasters Table Topics (impromptu speaking) Champion
* 2017 Black Belt - Chung Kuo Chuan Martial Arts
* 2016 Distinguished Toastmaster
* Winner of the 2013/14 Herb C. Stude Award for Educational Excellence
* 2014 District 7 Toastmasters Evaluation Contest Champion
* 2012 District 7 Toastmasters Humorous Speech Contest Champion

Current Volunteering:
* Little Toasties youth speaking club coach 2016 - Present
* Silicon Forest Toastmasters President 2017/18

Speech Coach - ericwinger.net
Speech Teacher - MIT School
Engineer - GemTalk Systems

**Comment by dalehenrich** [comment]
back to the bug .... The code you are using looks correct, but I think that the issue is that the package artifacts for the sample project are being left around in the symbol dictionary, so when you are ready to start a fresh set of samples, you should execute the following:
```Smalltalk
| user symList dict index |
	super setUp.
	user := System myUserProfile.
	symList := user symbolList.

	{(self _symbolDictionaryName).
	(self _symbolDictionaryName1).
	(self _symbolDictionaryName2).
	#'UnmanagedPackages'}
		do: [ :symDictName | 
			dict := symList objectNamed: symDictName.

			dict
				ifNotNil: [ 
					(dict at: GsPackagePolicy globalName otherwise: nil)
						ifNotNil: [ :policy | policy disable ].
					index := symList indexOf: dict.
					index > 0
						ifTrue: [ user removeDictionaryAt: index ] ] ].
	GsPackagePolicy current refreshSessionMethodDictionary
```
This is straight from my `setUp` method in my tests ... so you want to destroy **and** recreate the project and the symbol dictionaries freshly ... the symbol dictionaries can old onto packages and classes ... 

I haven't yet gotten to the point where the remove project cleans up all of it's artifacts, so until then I thinkthe above method needs to be used whenever you remove a project ...

**Comment by dalehenrich** [comment]
I looked at your project on github and don't see where the fileout is ... at the end of the day, the client code is going to need to be in the Rowan code base and since Rowan is running in a tODE stone, the tODE expressions can be used to work with the Rowan code in GemStone and this will be true until Rowan can load/save itself ... so if we are going to collaborate on the code we should do it using the Rowan repositroy ... you would be able to make bugfixes and extensions to the Rowan code yourself if you start using tODE Smalltalk expressions to look at diffs (optional) and write code to disk (there's a tODE smalltalk api for writing the code to disk, doing a git commit and pushing the code to github that you would use instead of filing out the symbol dictionary) ... let's talk on Monday

**Comment by dalehenrich** [comment]
I am a bit leary about running too much code in foos at the moment, because I don't want to interfere with what you are doing, so at the moment I'm not comfortable editting the code in place in test_rowan_340

**Comment by ericwinger** [comment]
I'm not sure we need to collaborate directly on the code itself. I just need to know the api's. 
I can always rebuild the rowan stone whenever you're ready.

**Comment by ericwinger** [comment]
I think by deleting and recreating the sample symbol dictionary, I've gotten past this issue. I will close.

**Comment by dalehenrich** [comment]
The collaboration comes into play when I start fiddling with methods that you may be using ... at this stage it would be easier for me to change your code if/when I change the api, then it would be to:
- leave the method there and deprecate --- for later cleanup 
- or make my changes without respect to how it affects your code ...

This will happen when Lisa or Richard or you say this method needs to be renamed ... which at this stage may happen quite a lot ...

I would like to be able to run your tests when I make my changes, so that I can be comfortable that I haven't broken your code inadvertently ...
