### ISSUE TITLE
Extension methods don't show changes

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#83]
If you change RowanSample1XXX>>xxxtension in RowanSample1-XXX package, then press show changes, the method won't appear in the change list. 

I presume this is because it is an extension method.

**Comment by dalehenrich** [comment]
I'll have to see if I can reproduce it ...

**Comment by dalehenrich** [comment]
using my latest commit (6ee21d2) I have confirmed that extension methods are not the culprit ... in general:
![image](https://user-images.githubusercontent.com/623951/39086973-27b4ff7e-454e-11e8-97fa-29ba6483d50b.png)
as I was able to modify and display changes for a method in the Tonel project (note I haven't been changing the guts to Rowan in my recent work, but working on loading Rowan with Rowan and other code bootstrapping issues like loading STON, Cypress, and Tonel, so that they can also be managed by Rowan ... aiming to get all of the code added to image for Rowan to be managed under Rowan --- getting very close).

I will load the RowanSample1 project and see if I can reproduce the problem there ...

**Comment by dalehenrich** [comment]
While the above method showed up in changes ... I did find that when I went to write the project to disk, it was not written out, so there is something funky going on and I will have to see what I can find out

**Comment by dalehenrich** [comment]
... I could not reproduce this problem ... bounce back to you, @ericwinger  ... perhaps you were expecting a changed in the wrong package (the same mistake I made [above](https://github.com/dalehenrich/Rowan/issues/83#issuecomment-383315853) ... you have to look for changes in the RowanSample1-Extensions package (where the method is located) to see the change:
![image](https://user-images.githubusercontent.com/623951/39089133-fbe06a92-4574-11e8-9c0d-fdb616e9736a.png)
A diff of RowanSample1-XXX will not show the change made to an extension method in another package

**Comment by ericwinger** [comment]
I'll have to reproduce. To clarify though, if an extension method in RowanSample1-XXX is changed I have to go to the package containing the extended class to see the change? That seems non-intuitive.

**Comment by dalehenrich** [comment]
we clarified that you go to the package with extensions to see change, but it is true that if you think you are looking at the extension package but looking at the core package you will not see the change ... I only mentioned this because it was a mistake that I had made when trying to reproduce the bug ...

**Comment by ericwinger** [comment]
I think I was looking at the wrong package. When I selected the extensions package, it seems to behave properly.
