### ISSUE TITLE
ArgumentError Unicode disallowed in string comparison while compiling method with unicode string

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#877]
I passed a unicode string to Behavior>>rwCompileMethod:category: and got this walkback. 
[20221118_rowanServerStackDump.txt](https://github.com/GemTalk/Rowan/files/10044582/20221118_rowanServerStackDump.txt)

**Comment by dalehenrich** [comment]
I assume that you do not have unicode compare enabled (`Unicode16 usingUnicodeCompares` is probably false) if you did this particular error would not show up ... Of course there are probably other issues lurking in the code  ... if you are embarking on attempting to support Unicode in Jadeite, you should wait until I have gone through the process of creating a RowanSample9 project that has unicode sprinkled liberally about the source code, class names, package names, etc..... @lisa, you and I should discuss what else needs to be done/required as well ... like enabling unicode comparisons.etc.

**Comment by ericwinger** [comment]
> I assume that you do not have unicode compare enabled (Unicode16 usingUnicodeCompares)
That is a correct assumption. If it's required, we should probably have Jadeite do that (when you're ready)

**Comment by lisa** [comment]
# `@lisa` User Notification

Hello! You're receiving this notice because you've tagged me, @lisa, on GitHub, likely in error. Lisa is a common first name, and happens to be mine. I use the @lisa username here on GitHub. While being tagged in various repositories is an interesting way for me to discover new projects, it's likely not your intention. Did you mean to tag someone else? Did you mean to use `@lisa` instead, in a [word as word](https://en.wikipedia.org/wiki/Use%E2%80%93mention_distinction) usage?

# Next Steps

I'm unsubscribing from this issue, pull request or project so if you meant to tag someone else to notify them, I would recommend that. If you meant to use my user ID as a plain string, without having GitHub notify me, you can do so by wrapping with backticks (the \` character), like so: `@lisa`.

**Comment by dalehenrich** [comment]
I know you are not subscribed, but if you care, `@lisa` happens to be the tag for a co-worker in slack, so you can probably understand how easy it would be to make this mistake ... I guess this makes me glad that `@dale` wasn't available when I joined github :)
