### ISSUE TITLE
SymbolDictionary does not understand #createLoadedPackageFromDefinition

### ISSUE THREAD

**Issue by ericwinger** [dalehenrich/Rowan#9]
I suspect I've done something wrong, but the failure is deep enough in the Rowan code that there may be something else going on. 

To reproduce, file in the attached .gs file and run: 
RowanMethodDefinitionService new createSampleMethod. 

(Note that the attached file is .txt because GitHub won't let me attach a .gs file :(  ) 

```
MessageNotUnderstood >> defaultAction @3 line 3
MessageNotUnderstood (AbstractException) >> _signalWith: @6 line 25
MessageNotUnderstood (AbstractException) >> signal @2 line 47
SymbolDictionary (Object) >> doesNotUnderstand: @10 line 10
SymbolDictionary (Object) >> _doesNotUnderstand:args:envId:reason: @8 line 13
RwGsPackageAdditionSymbolDictPatch >> createLoadedPackage @5 line 5
[] in RwGsPatchSetBasic >> addAndUpdateLoadedPackages @6 line 5
[] in Set >> do: @8 line 11
KeyValueDictionary >> keysDo: @20 line 18
Set >> do: @4 line 11
RwGsPatchSetBasic >> addAndUpdateLoadedPackages @2 line 5
RwGsPatchSetBasic >> apply @11 line 14
RwGsImage class >> applyModification: @11 line 9
RwPrjLoadTool >> loadProjectSetDefinition: @14 line 13
RwPrjLoadTool >> loadProjectDefinition: @6 line 7
RowanPackageDefinitionService >> createSamplePackage @11 line 10
RowanClassDefinitionService >> createSampleClass @5 line 5
RowanMethodDefinitionService >> createSampleMethod @5 line 6
GsNMethod class >> _gsReturnToC @1 line 1

[RowanServices.txt](https://github.com/dalehenrich/Rowan/files/1798286/RowanServices.txt)

~

**Comment by dalehenrich** [comment]
what was the selector that was not understood? In genereral the error description in addition to the stack would be useful ...

**Comment by dalehenrich** [comment]
If it's `updateLoadedPackage` then getting a MNU is *expected* only to the extent that I don't have a test case for that code path ... yet:) ... so I'll have to investigate in more detail ... thanks a ton ...

**Comment by dalehenrich** [comment]
Is the `RowanServices.txt` file the complete listing of your services filein?  ... It looks to me like I would like to get the services code packaged up sooner rather than later as we have entered the realm of collaboration already .... we'll definitely talk on Monday:)

Can I reproduce this bug in your test_rowan_340 stone? In order to write a test case, I only need to take a peak at the stack and inspect the receiver of `updateLoadedPackage` to see what the property changes were that caused this path to be taken ...

**Comment by dalehenrich** [comment]
I guessed wrong ... when I run on `test_rowan_340` the MNU is `createLoadedPackage` which is interesting ...

**Comment by dalehenrich** [comment]
Okay what's going on here is that the symbol dictionary `SampleSymbolDictionaryName` is a regular symbol dictionaryand for the time being Rowan symbol dictionaries need to be instances of RwGsPackageSymbolDictionary ... Rowan uses the method `RwGsImage class>>newOrExistingSymbolDictionaryNamed:` to create RwGsPackageSymbolDictionary when needed and so I assume that you might be adding  `SampleSymbolDictionaryName` to your symbol list instead of letting Rowan add it on demand

When RwGsPackageSymbolDictionary settles down, I'll figure out how to add this functionality to regular symbol dictionaries or not ...

**Comment by ericwinger** [comment]
Yup, that plus another tweak to load the project definition after adding the class did the trick. 
I was able to create ```#sampleMethod. Thanks.

**Comment by dalehenrich** [comment]
Hah I just noticed the the selector was in the title of issue ... tells you how much I read the titles of issues :)
